#!/bin/bash

# A script that will upload a file to an azure storage container

FileName="$1"
StorageAccount="ahclouduploadercli"
Container="ahcloudcontainer"

echo "The file to upload is: $FileName"

setup() { 
    # Install az cli
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    # Login
    az login --use-device-code
    echo "You're logged in."
}

setup

az storage blob upload --file $FileName --container-name $Container --account-name $StorageAccount --auth-mode login
